
// ///////////////////////////////////////////////////////////////////////////
//
// This file is written in AsciiDoc.
//
// ///////////////////////////////////////////////////////////////////////////
//
// When editing, please start each sentence on a new line.
// See https://asciidoctor.org/docs/asciidoc-recommended-practices/#one-sentence-per-line
// [one sentence-per-line writing technique.]
// This makes textual diffs of this file useful in a similar way to the way they work for code.
//
// //////////////////////////////////////////////////////////////////////////
:page-layout: page
:keywords: DFDL "data format"
= Data Format Description
:hide-uri-scheme:
:toc:
:toclevels: 20
:sectlinks:
:sectanchors:


== Outline/Topic Mind Map

[graphviz,"dataFormat",svg,svg-type=inline]
....
digraph dataFormat {
layout = dot
center=1
overlap=scale
splines=true
root="Data Format"
rankdir=TB
edge [dir=none, fontname="Noto Sans"]
node [fontname="Noto Sans"]


DF [label="Data\nFormat" style=bold shape=doublecircle ]

DF -> Representation
Representation -> Length
DF -> Statements
Statements -> Assertions
Statements -> Variables
DF -> "Defining Forms" -> Variables, EscapeSchemes, Formats
DF -> Correctness
Correctness -> WF
WF[label="well-formed"]
Correctness -> Valid -> XSD
XSD[label="XML Schema"]
Valid -> Schematron
XSD -> Facets -> "Pattern Facet" -> "XSD Regex"
DF -> Logical -> Infoset -> Valid
Logical -> Types
Logical -> Dimension
Logical -> Nilled
WF -> Assertions
Representation -> NilRep
Representation -> Empty

subgraph clusterEmpty {
Empty -> Defaulting
Defaulting -> "Use Nil As Default"
Empty -> "Empty Value Delimiter Policy"
Empty -> "Empty Value Parse Policy"
}

subgraph clusterNilRep {
NilRep
NilRep -> "Nil Values"
NilRep -> "Nil Value Delimiter Policy"
NilRep -> "Use Nil As Default"
}

subgraph dimension {
Dimension [ label="Dimension/\nRepetition" ]
}

subgraph length {
Length -> LengthKind
Length -> "Zero Length"
Length -> Empty
subgraph clusterLengthKind {
label="Length Kinds"
fontname="Noto Sans"
LengthKind -> Explicit, Implicit, Delimited, EndOfParent, Prefixed, Pattern, StopValue
Explicit -> "Fixed Length"
Explicit -> Stored
"Length Units" -> "Bits/Bytes", Chars
Implicit -> "Length Units"
Prefixed -> "Length Units"
Explicit -> "Length Units"
Pattern -> "DFDL Regex"
}
"DFDL Regex"
}

subgraph representation {
Representation ->  Text, Binary, Computed
Computed [label="Computed\n(No Representation)" ]
}
Representation -> POU

subgraph text {
Text
Text -> Lines
Lines [ label="Lines &\nLine Endings" ]
Text -> EncodingSystems

Text -> Padding -> Explicit

Delimited -> Initiators -> Discriminators
Delimited -> Separators -> "Separator Position"
Separators -> "Separator Suppression" -> "Zero Length"
Delimited -> Terminators
Delimited -> "Escape Schemes"

Text -> Fake
}

subgraph clusterEncodingSystems {
EncodingSystems [label="Encoding\nSystems\n(Character Sets)"]
EncodingSystems -> FixedWidth, Variable
EncodingSystems -> EncErrors
EncErrors [ label="Encoding/\nDecoding\nErrors" ]

FixedWidth [ label="Fixed Width" ]
FixedWidth -> SBCS, DBCS
DBCS -> "UCS-2"
FixedWidth -> LessThan8
LessThan8 [label="Less than 8\nBits Width"]
Variable [ label="Variable\nWidth" ]
Variable -> VCU
VCU [ label="1..N Code Units"]
Variable -> Shifting
VCU -> "Unicode UTF-8" -> "Variant CESU-8"
VCU -> "Unicode UTF-16"
}

subgraph binary {
Binary [URL="#binary-data-formats"]
Binary -> ByteOrder
ByteOrder -> BitOrder
Binary -> BinNumberRep
BinNumberRep [ label="Number\nRepresentation" ]
BinNumberRep -> BinaryNR
BinaryNR[label="Binary\n(Twos Complement)"]
BinNumberRep -> Packed, BCD
Binary -> Alignment
Binary -> Fake
Fake[label="Faking binary\nas text \nwith iso-8859-1"]
Fake -> BitsEncodings
BitsEncodings[label="bits, hex, and octal 'charsets'"]

}

Types->SimpleTypes
Types->ComplexTypes

SimpleTypes[label="Simple\nTypes"]
ComplexTypes[label="Complex\nTypes"]
ComplexTypes -> Sequences
ComplexTypes -> Choices

subgraph clusterSequences {
Sequences -> Ordered
Sequences -> Unordered
}

POU -> Assertions
POU -> Dimension
POU -> Backtracked
Asserts -> Discriminators
Assertions -> "Expression Test" -> Discriminators
Assertions -> "Pattern Test"
"Pattern Test" -> "DFDL Regex"
"Pattern Test" -> Asserts
"Expression Test" -> Asserts
subgraph clusterChoices {
Choices -> Backtracked -> Discriminators
Discriminators
Choices -> "By Dispatch"
}

Text -> "Regular Expressions" -> "DFDL Regex", "XSD Regex"

"DFDL Regex" -> Lookahead

subgraph clusterSimpleTypes {
SimpleTypes -> Integer, FloatingPoint
SimpleTypes -> FixedPoint
FixedPoint -> Scaled, Decimal
SimpleTypes -> DT
SimpleTypes -> String
SimpleTypes -> Opaque
Opaque [ label="Opaque\nBytes/Bits" ]
DT [label="Dates and Times"
URL="#dates-and-times"]
DT -> DateTime, Date, Time
}

}
....

== Binary Data Formats

NOTE: TBD: Section on binary data formats.

== Types

=== Dates and Times

For some reason in DFDL all the properties associate with dates and times contain the word calendar.

NOTE: This seems to be a legacy DFDL inherited from the Java programming language where the initial date/time-related library of classes were named using those terms, but these initial libraries were deemed insufficient.
The next re-invention of these libraries didn't want to be confused with the earlier one, despite sharing many concepts, so the term "calendar" is used to distinguish them.

== Textual Data Formats

Intuitively, _text_ is what we call data representations that use the characters of natural language alphabets, scripts, and numeric digits that are used by people for writing.

==== Text Terminology

- character
- lines
** line endings
- charset, encoding, character set
** ASCII, ISO-8859-1, UTF-8, EBCDIC
- code unit, width
- code point
- shifted encodings
- encode, decode
** Fallbacks, encoding errors, decoding errors
- Unicode
- glyph
- whitespace
** space, tab, LF, CR
- control characters
** CC0, CC1
** Unicode picture characters. Ex: &#x2403; (for ETX) or &#x2400; (for NUL)
- SBCS, DBCS


[graphviz,"dataFormat2",svg,svg-type=inline]
....
digraph dataFormat2 {

center=1
overlap=scale
splines=false
root="Advanced"
rankdir=LR
edge [dir=none]
node [fontname="Noto Sans"]


A [label="Advanced" style=bold shape=doublecircle ]

"Canonical Forms" -> "Round Trip"
A -> UC


subgraph UseCases {
UC [ label="Use Cases" ]
UC -> "Data\nIntegration"
UC -> "Data\nDirected\nRouting"
UC -> "Cybersecurity"

"Cybersecurity" -> "Covert Channels" -> "Canonical Forms"
}

A -> ParserTopics
ParserTopics -> StreamingOrNot
ParserTopics -> ErrorRecovery
ErrorRecovery -> VariablesWhenToUseThem
A -> UnparserTopics
UnparserTopics -> StreamingOrNot

A -> layers -> StreamingOrNot

A -> BLOBs

A-> "Parsing Syntax As Data"

A -> TDML
}
....



[graphviz,"dataFormat3",svg,svg-type=inline]
....
digraph dataFormat3 {
center=1
overlap=scale
splines=false
root="Advanced"
rankdir=LR
edge [dir=none]
node [fontname="Noto Sans"]

XSD -> NoRealArrays
XSD -> RootElements
XSD -> Namespaces -> Prefixes, TargetNS, DefaultNS
XSD -> SchemaLocation -> Resolver -> JarFiles -> AutomatedDependencyManagement -> SBT, Maven
Resolver -> "Compatibility" -> "XML Catalog"
XML -> "For Data" -> "Line Endings"
"For Data" -> "Illegal Characters"
"For Data" -> "Whitespace"
"For Data" -> Escaping -> CharEntities
Escaping -> "CDATA Bracketing"
XML -> XSD

}
....



[graphviz,"dataFormat4",svg,svg-type=inline]
....
digraph dataFormat4 {
// size = "7.5,10"
center=1
overlap=scale
splines=false
root="Advanced"
rankdir=LR
edge [dir=none]
node [fontname="Noto Sans"]

B [ label="Best Practices" ]
B -> "Units of Measure" -> "In type names"
"Units of Measure" -> "In element names"
B -> namespaces
B -> "directory structure" -> "Schema Composition"
B -> "simpleType derivations for lengthKind 'explicit'"
B -> "Transformation" -> Units
B -> BIST

}

....
